name: restowrent_v_two
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.4
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.0.1
  google_fonts: any
  flutter_screenutil: any
  font_awesome_flutter: any
  badges: any
  image_picker: any
  image_cropper: any
  flutter_switch: any
  awesome_dialog: any
  intl: any
  dio: any
  json_serializable: any
  http: ^0.13.4
  lottie: 1.3.0
  cached_network_image: 3.2.1
  hive: ^2.2.3
  hive_flutter: 1.1.0
  getwidget: 3.0.1
  socket_io_client: ^2.0.0
  ticket_widget: 0.0.1
  rounded_loading_button: 2.1.0
  path_provider: ^2.0.11
  flutter_animated_dialog: 2.0.1
  audioplayers: ^1.0.1
  settings_ui: 2.0.2
  dropdown_button2: 1.7.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
    - assets/image/food/
    - assets/lottie/
    - assets/sounds/
  uses-material-design: true

