name: restowrent_v_two
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.4
  get: any
  animated_bottom_navigation_bar: any
  google_fonts: any
  flutter_screenutil: any
  font_awesome_flutter: any
  badges: any
  image_picker: any
  image_cropper: any
  flutter_switch: any
  progress_state_button: any
  awesome_dialog: any
  intl: any
  dio: any
  json_serializable: any
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
    - assets/image/food/
  uses-material-design: true

