name: restowrent_v_two
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.4
  get: any
  animated_bottom_navigation_bar: any
  google_fonts: any
  flutter_screenutil: any
  font_awesome_flutter: any
  badges: any
  image_picker: any
  image_cropper: any
  flutter_switch: any
  awesome_dialog: any
  intl: any
  dio: any
  json_serializable: any
  http: ^0.13.4
  lottie: 1.3.0
  cached_network_image: 3.2.1
  hive: ^2.2.2
  hive_flutter: 1.1.0
  getwidget: 3.0.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  ticket_widget: 0.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: 2.1.11
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
    - assets/image/food/
    - assets/lottie/
  uses-material-design: true

